# Use the official Maven image with Java 17
FROM eclipse-temurin:17

# Install OpenSSH server 
#Uncomment the following line if you want to enable SSH access to the container
#RUN apt-get update && apt-get install -y openssh-server

# Create necessary SSH directory
RUN mkdir -p /run/sshd

# Create a new user
RUN useradd -ms /bin/bash deployuser

# Set password for the user (replace 'password' with your secure password)
RUN echo "${DEPLOYUSER}:${DEPLOYUSER_PASSWORD}" | chpasswd

# Ensure the SSH directory exists and set permissions
RUN mkdir /home/deployuser/.ssh && chmod 700 /home/deployuser/.ssh

# Create the directory for app deployment and set appropriate permissions
RUN mkdir -p /app/backend && chown deployuser:deployuser /app/backend

# Set the working directory to the app deployment directory
WORKDIR /app/backend

# Expose the SSH port
EXPOSE 22

# Expose the port for external connections (for the application itself)
EXPOSE 8080

# Start the SSH service in the foreground
CMD ["/usr/sbin/sshd", "-D"]
